### ISSUE TITLE
Click the link and preview ONLY the front, with the back 1 button away?

### ISSUE THREAD

**Issue by ccchan234** [ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer#13]
hi sorry I am new to anki and plugins.

this Q is mentioned in old issues, i dont see anwser there but seems they closed it:
https://github.com/ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer/issues/1

i can put a cidd link to an anki card/note,
when click on it, it shows a preview of front+back, the back contains the answer which i want it to be 1 button away from the question page (the front page).

did i missed something? i am already on the latest version.
the above thread discussed this but seems they turn in to what IR note (incremental reading) which I dunt use.

thankyou.

and thankyou for the plugin.

**Comment by ijgnd** [comment]
change the add-on setting `"card_preview__default_is_answer"`.

If this doesn't solve your problem:
- reopen the issue
- describe the exact steps to reproduce your problem while all other add-ons are disabled (see https://faqs.ankiweb.net/when-problems-occur.html)
