### ISSUE TITLE
add backlinks (option for current note from editor/tablecontext menu or for all notes from main window tools)

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer#16]
these seem popular, maybe this minimal, manual implementation is better than nothing

maybe do it automatically: when note is added or note is edited in the browser?

**Comment by jjjj4444** [comment]
truely needed

**Comment by jjjj4444** [comment]
truly needed

**Comment by ijgnd** [comment]
I just uploaded a new version with basic support for backlinks for Anki 2.1.55 and newer.
