### ISSUE TITLE
在broswer里预览卡片时，无法显示链接

### ISSUE THREAD

**Issue by pzh200707** [ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer#2]
在主窗口复习时，可以显示链接，但是在浏览器里预览某个卡片时，无法显示超链接
![image](https://user-images.githubusercontent.com/26104496/74417143-311db680-4e81-11ea-9171-a92e11b95ba5.png)

**Comment by ijgnd** [comment]
this will be available in the next version of this add-on. This depends on a new feature in Anki itself that has not been released yet. Once this required feature of Anki is available to regular users in a regular release of Anki I'll release a new version of my add-on.

**Comment by ijgnd** [comment]
you were lucky. Today Anki 2.1.20 was released and includes the necessary underlying feature.

Try the latest version for 2.1.20 from https://ankiweb.net/shared/info/1423933177 and let me know if it works.

**Comment by pzh200707** [comment]
![image](https://user-images.githubusercontent.com/26104496/74581557-cd63cc80-4feb-11ea-96b2-b012dc490a24.png)

Crashed. I've tried disabling other addons and reinstall the addon, the issue is still there. 

Version 2.1.20 (1fbd925f)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
win10 x64

**Comment by ijgnd** [comment]
You use an old version of Anki: "Version 2.1.20 (1fbd925f)" means "beta9". But you need the release version of 2.1.20 from https://apps.ankiweb.net/ .

**Comment by pzh200707** [comment]
Thank you soooo much! It works!
![image](https://user-images.githubusercontent.com/26104496/74586715-69f69080-5025-11ea-874f-2d0300b33ea8.png)
