### ISSUE TITLE
Opening new window

### ISSUE THREAD

**Issue by drsnn** [ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer#3]
Hi ijnd 

Thank you very much for this good addon. When i click link it opens in new window. Previously i can open link as a popup window without leaving page. I think it is related my other addons or i am doing somthing wrong.

https://imgur.com/WX4rQof

**Comment by ijgnd** [comment]
I must confess I still don't understand. Could you a) reword and extend your post and b)  make screencast how it used to work. 

about b): The old version from March can be downloaded from [here](https://github.com/ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer/releases/download/0.1/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer__2020-03-03.ankiaddon). 

video: [installing ankiaddon files from outside of ankiweb](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation.gif)

&nbsp;

Also it seems that you have MacOS and force new windows into tabs (or some window managing program). Can you disable this? For me on my computers the Preview is in a separate window.

**Comment by drsnn** [comment]
I am sorry my English is not so good. May be i couldnt explain clearly. 

I want to open link like popup. In previously i can use addon like popup. But it links open on the top   right not as popup window. 

I disabled some other addons but it is contuning . I gues that it is related to anki itself. I upgraged to last version 2.26 for mac. I think it may be related to the addons. 

Thank you again for awasome addon.

**Comment by ijgnd** [comment]
Another idea: go to the browser window. In the upper right there's a "preview" button. Click it: Do you get a tab or a window?

If you get a tab: My guess is that you have some setting in your MacOS that forces windows into tabs. I would google and maybe search help.ankiweb.net or reddit.com/r/anki. Maybe relevant: https://www.reddit.com/r/Anki/comments/7myp7r/force_tabs_in_anki/ ?? But I don't have a Mac.

Good Luck. I don't see what I can do at the moment. So I'm closing this issue for now. If you run into other problems just let me know. Maybe I'll have better ideas the next time.

**Comment by drsnn** [comment]
Yes, finally i solved it, as you said it was related to dock setting . Thank you very very much. You are genuis.
