### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer#4]
Hi.
I keep deleting cards while copying a cards id (Never thought I'd want a confirm delete button) since they're directly adjacent.
![2020-06-13_09-40-19](https://user-images.githubusercontent.com/13769570/84560099-204a5800-ad30-11ea-985e-6388c3091852.png)
Some hotkeys would be appreciated. 
Thanks for your work on this addon.

**Comment by ijgnd** [comment]
I just uploaded a new version to ankiweb that allows to set shortcuts for the browser. If you find any problems let me know.

**Comment by ghost** [comment]
Thanks. ijgnd. Works perfectly.
